### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by jcahail** [azavea/franklin#267] opened 2020-06-10 13:23 UTC

**Comment by jisantuc** [comment] 2020-06-12 21:18
It looks from #272 that the problem was unconstrained container sizes in generators. Work on this issue should probably be to fix all the PRs that accumulated from scala-steward while our CI was bad.

**Comment by jisantuc** [comment] 2020-06-16 16:43
Confirmed that bounding the sizes of container generators has made CI much more reliable, lots of PRs merged this morning after rebase / build for evidence that this is fine now

**Closed by jisantuc** 2020-06-16 16:43 UTC
Labels: farfelu
